services:
  - type: web
    name: seedora-backend
    env: node
    buildCommand: cd Backend && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd Backend && node index.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
